a = (input('Digite algo ='))
print('Tipo primitivo = ', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumério?', a.isalnum())
print('Está em minusculo?', a.islower())
print('Está em maisuculo?', a.isupper())
print('está capitaliszada?', a.istitle())
